---
title: "ReportBatteryTests"
output: html_document
params:
  path: "/Users/ibernabe/IntellijProjects/tests_holger_rec/15_11_2018_13_37_57/analisis/"
---
<!-- path recibe un parametro, por defecto es: ./analisis-->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(htmlTable)
library(knitr)
library(ggplot2)
options(table_counter = TRUE)
```

## Tabla resumen para el paper
```{r TablaPaper, echo=FALSE}

#Configuraciones globales
options(OutDec= ",") #Indico que la , representa los decimales
#setwd("/Users/ibernabe/IntellijProjects/Bike3STests/paperAT2018/allbikes/test/31_10_2018_12_06_41")
#setwd(params$path)

listDirectoryToCSVs <- list.dirs(path = params$path, full.names = TRUE, recursive = TRUE)

# Creo los dataFrames necesarios:
tablaTimeToStation <-data.frame()
tablaCyclingTime <-data.frame()
tablatimeToDestinationPlace <-data.frame()
tablatimeToTal <-data.frame()

tablaPaper <-data.frame()
tablaStationBalancingQuality <-data.frame()
tablaGlobalValues <-data.frame()

#Proceso cada uno de los ficheros
for (k in 1:length(listDirectoryToCSVs)){
  if (k!=1){
    # Proceso usuarios
    # ==========================================================
    path = paste(listDirectoryToCSVs[k], "/users.csv")
    path = gsub(" /","/",path)
    # Leo fichero
     users  <- read.csv(path,
                     header = TRUE,
                     sep = ";"
                     )
    
    # Elimino las filas que tienen la celda en blanco
    timeToStation <- users$time.to.origin.station[!is.na(users$time.to.origin.station)]
    cyclingTime <- users$cycling.time[!is.na(users$cycling.time)]
    timeToDestinationPlace <- users$time.to.destination.place[!is.na(users$time.to.destination.place)]
    
    #Modifico los textos en el dataframe
    nameTest <- gsub("/users.csv","",path)
    nameTest <- gsub(params$path,"",nameTest)
    nameTest <- gsub("/","",nameTest)
    
    
    #Creo una columna por cada iteración
    valueTimeToStation <-format( mean (timeToStation)/60, digits=2, nsmall=2)
    timeToStationAux <- t(c(nameTest,valueTimeToStation))
    
    valueCyclingTime <-format( mean (cyclingTime)/60, digits=2, nsmall=2)
    cyclingTimeAux <- t(c(nameTest,valueCyclingTime))
    
    valueTimeToDestinationPlace <-format( mean (timeToDestinationPlace)/60, digits=2, nsmall=2)
    timeToDestinationPlaceAux <- t(c(nameTest,valueTimeToDestinationPlace))
  
    #Añado a la tabla las columnas
    (tablaTimeToStation<-rbind(tablaTimeToStation,timeToStationAux))
    (tablaCyclingTime<-rbind(tablaCyclingTime,cyclingTimeAux))
    (tablatimeToDestinationPlace<-rbind(tablatimeToDestinationPlace,timeToDestinationPlaceAux))
    
    #Calculo la tabla con los valors máximos
    
    total <- (mean (timeToStation) + mean (cyclingTime) +mean (timeToDestinationPlace))/60   
    total <-  format(total, digits=2, nsmall=2)
    tablatimeToTal <-rbind(tablatimeToTal,t(c(nameTest,total)))
    
    users.SH <- nrow(users[users$Successful.bike.rentals=='1',]) #Succesfull hires
    users.N <- nrow(users) #Numero total de usuarios
    users.DS <- users.SH / users.N
    
    users.SR <- nrow(users[users$Successful.bike.returns=='1',]) #Succesfull return
    users.RS <- users.SR/users.SH
    

    #Usuarios que han conseguido alquilar una bici
    users.hanAlquiladoBici <- users[users$Successful.bike.rentals=='1',]
    users.FH.aux <- users.hanAlquiladoBici[users.hanAlquiladoBici$Failed.bike.rentals>'0',] #Failed rentals
    users.FH.aux <- users.FH.aux [users.FH.aux$Failed.bike.rentals<'3',] #Failed rentals
    users.FH <- sum(users.FH.aux$Failed.bike.rentals) #Failed rentals
    users.HE <- users.SH / (users.SH+users.FH)
    
    users.FR <- sum(users$Failed.bike.returns) #Failed returns
    users.RE <- users.SR / (users.SH + users.FR)
  
    #Aplico un formato para la visualización
    users.DS <- format(users.DS, digits=4, nsmall=4) #Formateo el valor
    users.RS <- format(users.RS, digits=4, nsmall=4) #Formateo el valor
    users.HE <- format(users.HE, digits=4, nsmall=4) #Formateo el valor
    users.RE <- format(users.RE, digits=4, nsmall=4) #Formateo el valor
    
     
    #print(paste("users.FR  ",users.FR ))
    #print(paste("users.SH  ",users.SH ))
    #print(paste("users.SR  ",users.SR ))
    #print(paste("users.RE  ",users.RE ))
    
  
    # Proceso empty Time
    # ==========================================================
    path = paste(listDirectoryToCSVs[k], "/empty_stations.csv")
    path = gsub(" /","/",path)
   
    # Leo fichero
    estaciones  <- read.csv(path,
                     header = TRUE,
                     sep = ";"
    )
    estaciones.Total.SinBicis  <- sum(estaciones$Total.time)/60 #Resultado en minutos
    estaciones.Total.SinBicis <- format(estaciones.Total.SinBicis, digits=2, nsmall=2) #Formateo el valor
  
    
   # Proceso obtener Desviación
    # ==========================================================
    path = paste(listDirectoryToCSVs[k], "/stationBalanceQuality.csv")
    path = gsub(" /","/",path)
   
    # Leo fichero
    balancingQuality  <- read.csv(path,
                                  header = TRUE,
                                  sep = ";"
    )
    balancingQuality.media  <- mean(balancingQuality$balancing.quality) #
    balancingQuality.media <- format(balancingQuality.media, digits=2, nsmall=2) #Formateo el valor
  
    #Relleno la tabla
    rowTablaPaper <- t(c(nameTest,users.DS,users.HE,users.RE,estaciones.Total.SinBicis,balancingQuality.media))
    tablaPaper<-rbind(tablaPaper,rowTablaPaper)
    
    #Relleno dfTablaStationBalancingQuality
    value <-format( mean (balancingQuality$balancing.quality), digits=2, nsmall=2)
    stationBalancingQualityAux <- t(c(nameTest,value))

    #Añado a la tabla las columnas
    tablaStationBalancingQuality<-rbind(tablaStationBalancingQuality,stationBalancingQualityAux)
    
    #
    #===============================================
    path = paste(listDirectoryToCSVs[k], "/global_values.csv")
    path = gsub(" /","/",path)
   
    # Leo fichero
    globalValues  <- read.csv(path,
                                  header = TRUE,
                                  sep = ";"
    )
 
  Aux <-  t(c(nameTest, 
              format( globalValues$Demand.satisfaction, digits=2, nsmall=2),
              format( globalValues$Hire.eficiency, digits=2, nsmall=2),
              format( globalValues$Return.eficiency, digits=2, nsmall=2)))
  
  #Añado a la tabla las columnas
  tablaGlobalValues<-rbind(tablaGlobalValues,Aux)

    
  }
}
  
htmlTable(tablaPaper,
          align = "l", # Alineación a la izquierda
          caption = "Experiment results",
          rnames = c(rep(paste("",""),nrow(tablaPaper))),
          header =  paste(c("Strategy","DS","HE","RE", "Empty Time (min)","Deviation")),
          align.header = "l",
          col.rgroup = c("none", "#F7F7F7"), # coloreo las filas impares
          css.class= "table"
)
```


## Datos del usuario {.tabset .tabset-fade}

### Tiempo del usuario a la estación origen
```{r listFiles, echo=FALSE}
htmlTable(tablaTimeToStation,
          align = "l", # Alineación a la izquierda
          caption = "Medias de time.to.origin.station",
          rnames = c(rep(paste("",""),nrow(tablaTimeToStation))),
          header =  paste(c("Test","Medias (min.)")),
          align.header = "ll",
          col.rgroup = c("none", "#F7F7F7"), # coloreo las filas impares
          css.class= "table"
)
#Dibujo el grafico de barras
dataSet.estrategia = as.vector(t(tablaTimeToStation[1]))
dataset.valor = as.vector(t(tablaTimeToStation[2]))

dataset <- data.frame(dataSet.estrategia, dataset.valor)

library(ggplot2)
ggplot(data=dataset, aes(x=dataSet.estrategia, y=dataset.valor  )) + 
  coord_flip() + theme_grey() +
  xlab("Estrategia") +  ylab("Minutos") +
  geom_bar( stat="identity", fill="#C678EF", width= 0.50) #Grosor de la barra
```

### Tiempo del usuario en la bicicleta
```{r listFiles.cycling.time, echo=FALSE}
htmlTable(tablaCyclingTime,
          align = "l", # Alineación a la izquierda
          caption = "Medias de cycling.time",
          rnames = c(rep(paste("",""),nrow(tablaCyclingTime))),
          header =  paste(c("Test","Medias (min.)")),
          align.header = "ll",
          col.rgroup = c("none", "#F7F7F7"), # coloreo las filas impares
          css.class= "table"
)
#Dibujo el grafico de barras
dataSet.estrategia = as.vector(t(tablaCyclingTime[1]))
dataset.valor = as.vector(t(tablaCyclingTime[2]))

dataset <- data.frame(dataSet.estrategia, dataset.valor)


ggplot(data=dataset, aes(x=dataSet.estrategia, y=dataset.valor  )) + 
  coord_flip() + theme_grey() +
  xlab("Estrategia") +  ylab("Minutos") +
  geom_bar( stat="identity", fill="#C678EF", width= 0.50) #Grosor de la barra
```

### Tiempo del usuario al lugar de destino
```{r listFiles.time.to.destination.place, echo=FALSE}
htmlTable(tablatimeToDestinationPlace,
          align = "l", # Alineación a la izquierda
          caption = "Medias de destination.place",
          rnames = c(rep(paste("",""),nrow(tablatimeToDestinationPlace))),
          header =  paste(c("Test","Medias (min.)")),
          align.header = "ll",
          col.rgroup = c("none", "#F7F7F7"), # coloreo las filas impares
          css.class= "table"
)
#Dibujo el grafico de barras
dataSet.estrategia = as.vector(t(tablatimeToDestinationPlace[1]))
dataset.valor = as.vector(t(tablatimeToDestinationPlace[2]))
dataset <- data.frame(dataSet.estrategia, dataset.valor)

ggplot(data=dataset, aes(x=dataSet.estrategia, y=dataset.valor  )) + 
  coord_flip() + theme_grey() +
  xlab("Estrategia") +  ylab("Minutos") +
  geom_bar( stat="identity", fill="#C678EF", width= 0.50) #Grosor de la barra

```

### Tiempo Total
```{r listFiles.timeTotal.to.destination.place, echo=FALSE}
htmlTable(tablatimeToTal,
          align = "l", # Alineación a la izquierda
          caption = "Medias de destination.place",
          rnames = c(rep(paste("",""),nrow(tablatimeToTal))),
          header =  paste(c("Test","Medias (min.)")),
          align.header = "ll",
          col.rgroup = c("none", "#F7F7F7"), # coloreo las filas impares
          css.class= "table"
)
#Dibujo el grafico de barras
dataSet.estrategia = as.vector(t(tablatimeToTal[1]))
dataset.valor = as.vector(t(tablatimeToTal[2]))
dataset <- data.frame(dataSet.estrategia, dataset.valor)

ggplot(data=dataset, aes(x=dataSet.estrategia, y=dataset.valor  )) + 
  coord_flip() + theme_grey() +
  xlab("Estrategia") +  ylab("Minutos") +
  geom_bar( stat="identity", fill="#C678EF", width= 0.50) #Grosor de la barra

```

##

<hr>
<br>
<!--
### Calidad de balanceo de las estaciones 
-->
```{r listFiles.demand.satisfation, echo=FALSE}



#htmlTable(tablaStationBalancingQuality,
#          align = "l", # Alineación a la izquierda
 #         caption = "stationBalancingQuality",
  #        rnames = c(rep(paste("",""),nrow(tablaStationBalancingQuality))),
   #       header =  paste(c("Test", "Calidad")),
    #      align.header = "ll",
     #     col.rgroup = c("none", "#F7F7F7"), # coloreo las filas impares
      #    css.class= "table"
#)
```


<hr>
<br>
<!--
### Comparación de los valores globales
-->
```{r global_values, echo=FALSE}

# Esta tabla saca los valores leídos directamente del fichero global_values que no funciona bien

#htmlTable(tablaGlobalValues,
#          align = "l", # Alineación a la izquierda
 #         caption = "global_values",
  #        #rnames = c(rep(paste("",""),nrow(tablaStationBalancingQuality))),
   #       header =  paste(c("Test", "Demand Satisfaction","Hire efficiency", "Return efficiency")),
   #       align.header = "ll",
    #      col.rgroup = c("none", "#F7F7F7"), # coloreo las filas impares
     #     css.class= "table"
#)

```