package es.urjc.ia.bikesurbanfleets.users;

public enum UserType {
    USER_RANDOM, USER_TOURIST, USER_COMMUTER, USER_AVAILABLE_RESOURCES, USER_REASONABLE, 
    USER_DISTANCE_RESTRICTION, USER_UNINFORMED, USER_INFORMED
}
